In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
from matplotlib import cm
from matplotlib.tri import Triangulation

import ast

In [2]:
def parse_results(file_name):
    grid_search_results = []
    with open(file_name, 'r') as file:
        for line in file.readlines():
            if line[0:4] == '----':
                grid_search_results.append([])
                continue

            if line[0] == '(':
                fixed_line = '[' + line.strip().replace(') (', '), (') + ']'
                params = ast.literal_eval(fixed_line)
                nested = [list(zip(key.split(','), np.array(val).flatten())) for (key, val) in params]
                unnested = [item for sublist in nested for item in sublist]
                grid_search_results[-1].append({key: val for (key, val) in unnested})
                grid_search_results[-1].append([])
                continue

            result = line

            if result[0] == '[':
                grid_search_results[-1][-1].append(ast.literal_eval(result))
                continue

    grid_search_results = [(params, np.array(values)) for params, values in grid_search_results]
    return grid_search_results

In [4]:
hyp_res = parse_results('grid_search_results/hyp_broad_search_50_cutoff.txt')
# euc_res = parse_results('grid_search_results/tom_euc_overall-liking_400.txt')

In [6]:
hyp_params = np.array([p for p, _ in hyp_res])
hyp_values = np.array([v for _, v in hyp_res])

# euc_params = np.array([p for p, _ in euc_res])
# euc_values = np.array([v for _, v in euc_res])

hyp_values.shape

(72, 5, 50)

In [46]:
last = hyp_values[-1]
# repeated_last = np.repeat(last[np.newaxis, ...], 9, axis=0)
extended_hyp = np.concatenate((hyp_values, hyp_values[-9:]), axis=0)

extended_hyp.shape

(81, 5, 50)

In [47]:
(extended_hyp.mean(axis=1).mean(axis=0) / extended_hyp.mean(axis=1).mean(axis=0).max())

array([0.71892392, 0.82833852, 0.8776104 , 0.90593009, 0.92502355,
       0.93885726, 0.94905978, 0.95653569, 0.96234253, 0.96683899,
       0.9705315 , 0.97367664, 0.97633575, 0.97854154, 0.98021196,
       0.98209436, 0.98364224, 0.98513093, 0.98630006, 0.98729792,
       0.98830944, 0.98896138, 0.98974719, 0.99057806, 0.99121302,
       0.99190675, 0.99240638, 0.99276035, 0.99340857, 0.99384069,
       0.99437551, 0.9947761 , 0.99519633, 0.99546848, 0.99585908,
       0.99624004, 0.99651976, 0.99685836, 0.99705058, 0.99745761,
       0.99786952, 0.99804287, 0.99825635, 0.99861292, 0.99879301,
       0.99916525, 0.99929335, 0.99951826, 0.99978482, 1.        ])

In [57]:
round_ext_hyp = np.round(extended_hyp, 4)

# print(round_ext_hyp.mean(axis=1)[:,-1][:27][:9].mean())
# print(round_ext_hyp.mean(axis=1)[:,-1][:27][9:18].mean())
# print(round_ext_hyp.mean(axis=1)[:,-1][27:54][:9].mean())
# print(round_ext_hyp.mean(axis=1)[:,-1][27:54][9:18].mean())

print(round_ext_hyp.mean(axis=1)[:,-1][:27][18:][::3])

print(round_ext_hyp.mean(axis=1)[:,-1][27:54][18:][::3])

# print(round_ext_hyp.mean(axis=1)[:,-1][54:])

[0.36824 0.35638 0.31898 0.36934 0.3589  0.32558 0.37004 0.35972 0.32844]
[0.36824 0.36934 0.37004]
[0.37034 0.37182 0.37262]


In [ ]:
best_params = {
    'model_type': ['hyp'],
    'num_hidden_layers': [1],
    'layer_size': [256],
    'lr': [0.01],
    'weight_decay': [0.001],
    'batch_size': [1024],
    'epochs': [50],
    'curvature': [-1]
}