In [2]:
import numpy as np

In [20]:
type_groups = [np.array([12,  8,  2,  7]),
               np.array([11,  9]),
               np.array([15,  5]),
               np.array([19,  6, 18]),
               np.array([ 1, 14, 21]),
               np.array([ 3, 17,  0]),
               np.array([10]),
               np.array([13]),
               np.array([16, 20,  4])]

type_groups = [np.array([0,1]),
                np.array([2,3]),
                np.array([4,5,6])]

In [21]:
type_groups

[array([0, 1]), array([2, 3]), array([4, 5, 6])]

In [22]:
NUM_CLASSES = sum(len(group) for group in type_groups)

def generate_disctance_matrix(group_value=0.5):
    d_matrix = np.ones([NUM_CLASSES,NUM_CLASSES]) - np.diag(np.ones(NUM_CLASSES))

    for group in type_groups:
        for i, x in enumerate(group[:-1]):
            for j, y in enumerate(group[i+1:]):
                d_matrix[x,y] = group_value
                d_matrix[y,x] = group_value

    return d_matrix

In [93]:
d_matrix = generate_disctance_matrix()
for d in d_matrix:
    print(list(d))

[0.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0]
[0.5, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 0.0, 0.5, 1.0, 1.0, 1.0]
[1.0, 1.0, 0.5, 0.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 0.0, 0.5, 0.5]
[1.0, 1.0, 1.0, 1.0, 0.5, 0.0, 0.5]
[1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.0]


In [94]:
gt   = np.array([0,1,2,3,4,5,6,6])
pred = np.array([[1,0,0,0,0,0,0],
                 [0,1,0,0,0,0,0],
                 [0,0,0,1,0,0,0],
                 [0,0,1,0,0,0,0],
                 [0,0,1,0,0,0,0],
                 [0,0,0,1,0,0,0],
                 [0,0,0,0,1,0,0],
                 [0,0,0,0,0,0,1]
                 ])

In [95]:
import torch.nn.functional as F
import torch

In [96]:
torch.Tensor(pred).shape

torch.Size([8, 7])

In [97]:
gt.shape

(8,)

In [98]:
print(F.cross_entropy(torch.Tensor(pred), torch.Tensor(gt).to(torch.long), reduction='none'))
print(F.cross_entropy(torch.Tensor(pred), torch.Tensor(gt).to(torch.long), reduction='none') * d_matrix[pred.argmax(axis=1), gt])

tensor([1.1654, 1.1654, 2.1654, 2.1654, 2.1654, 2.1654, 2.1654, 1.1654])
tensor([0.0000, 0.0000, 1.0827, 1.0827, 2.1654, 2.1654, 1.0827, 0.0000],
       dtype=torch.float64)


In [99]:
d_matrix[pred.argmax(axis=1), gt]

array([0. , 0. , 0.5, 0.5, 1. , 1. , 0.5, 0. ])